server:
  port: 8081

logging:
  config: classpath:logback/logback-dev.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #����com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8 #����serverTimezone����ʱ������
    username: root
    password: 123456
